data:
  AzureWebJobsStorage: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWZ1bmNhcHB1ZDI7QWNjb3VudEtleT1sSWlTMnFnSkg1K0pFaWJvcGREcENycEhuOGdnbUhiVVZWeURtOXlJTVpLYTdEOTJPcWNRU1p6N3NXZld2K0ZocXM4b290ZnlncWcrK0FTdC9Ka09GUT09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  FUNCTIONS_EXTENSION_VERSION: fjQ=
  WEBSITE_CONTENTAZUREFILECONNECTIONSTRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWZ1bmNhcHB1ZDI7QWNjb3VudEtleT1sSWlTMnFnSkg1K0pFaWJvcGREcENycEhuOGdnbUhiVVZWeURtOXlJTVpLYTdEOTJPcWNRU1p6N3NXZld2K0ZocXM4b290ZnlncWcrK0FTdC9Ka09GUT09O0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ=
  WEBSITE_CONTENTSHARE: ZnVuY2FwcHVkMjA2ZDYyOA==
  MyDbConnection: bW9uZ29kYjovL2Nvc21vc3VkOnVTM05SSDhkUTlBTUJoenB4YUJtYTM0Y0hqN1hKbFFBV3RDREhCUmVoQWh3RHhjbGhDbjIyTG9vbHpEeVFwV0VDUzcxbzlrNTVxSUZiTU9uWTNzWkR3PT1AY29zbW9zdWQubW9uZ28uY29zbW9zLmF6dXJlLmNvbToxMDI1NS8/c3NsPXRydWUmcmVwbGljYVNldD1nbG9iYWxkYiZyZXRyeXdyaXRlcz1mYWxzZSZtYXhJZGxlVGltZU1TPTEyMDAwMCZhcHBOYW1lPUBjb3Ntb3N1ZEA=
apiVersion: v1
kind: Secret
metadata:
  name: funcappud2aks
---
data:
  host.master: eWl2SHU0Q1Etb3RoNV8tUHlKT2g3NlZyVzRFcUxRUGFncHVTWmZPa2dYcUFBekZ1RF8tWUVBPT0=
  host.function.default: c3ZsbTdZU1hqQ2pRN0xLUXM1dUJiRUNxMUYwQ1otOTBaVm9nR0QwNzNiSnpBekZ1VEt5VHF3PT0=
  host.systemKey.default: dzkwSXVlX181MDV2OWx6YUc5NURYNWY3eXFYSEFKMFJIdkZSTmVXUjh6UmpBekZ1UmNrMzNnPT0=
  functions.createadvertisement.default: Vk9jYm40TFY2d3c1U0c2S3RKMktvNF9wRWdSdkctREhQWm9tenNGTlhnQUNBekZ1eHpxb19RPT0=
  functions.deleteadvertisement.default: ZnhFc2VNeEVvbFg0N1BuTWl3OFlMQmVGc0lQTE1hTzJVSjNVZHY0T3UzYUxBekZ1VE81SzZnPT0=
  functions.getadvertisement.default: dnZna3M5emVjNnl4OHdOUlVMU09hUkdzcXlySVZRVjJOT0x0X2RnUTh4bE9BekZ1NFFjc1hnPT0=
  functions.getadvertisements.default: UENvSTk5ZFZnQVBEendES0U5NlhTN2VxdFRkNGZRNTZ4SFdwNkpEdGt0S2VBekZ1ZURHSFpnPT0=
  functions.getpost.default: U1hHaUNVOFdrSkZNTVpiV1lFX3MyZ3JlMm0xTUd0eTVfbnpHNFVjeHVzZS1BekZ1WnBZYjVRPT0=
  functions.getposts.default: dWtucXJJS2o3cGxxWEo3a3VjSUd1N25zVnYtNDVOSnk0NlZWRjdSWE9iczhBekZ1S2dqb0NRPT0=
  functions.updateadvertisement.default: UEJTc1dsSzBDa1ZQYmxFenV6TWxacGloWmtZUVdNVkNQMzlRdDdwakxsSHJBekZ1MjlCbUZ3PT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-funcappud2aks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: funcappud2aks-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: funcappud2aks-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: funcappud2aks-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: funcappud2aks-http
spec:
  selector:
    app: funcappud2aks-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: funcappud2aks-http
  labels:
    app: funcappud2aks-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funcappud2aks-http
  template:
    metadata:
      labels:
        app: funcappud2aks-http
    spec:
      containers:
      - name: funcappud2aks-http
        image: acrud.azureacr.io/funcappud2aks:latest
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-funcappud2aks
        envFrom:
        - secretRef:
            name: funcappud2aks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: funcappud2aks-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: funcappud2aks
  labels:
    app: funcappud2aks
spec:
  selector:
    matchLabels:
      app: funcappud2aks
  template:
    metadata:
      labels:
        app: funcappud2aks
    spec:
      containers:
      - name: funcappud2aks
        image: acrud.azureacr.io/funcappud2aks:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: funcappud2aks
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: funcappud2aks-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: funcappud2aks
  labels: {}
spec:
  scaleTargetRef:
    name: funcappud2aks
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

